Initial seed
Dragon-Scaling/photo_gallery_service pull request #1
Opened 2019-09-14 17:07 UTC by justindchan

Postgres seed implemented, working on Mongo implementation and write to CSV

2019-09-14 17:19 UTC, justindchan commented
@rfagg805 tagging for visibility

2019-09-14 17:21 UTC, rfagg805 commented on README.md
> +  - hhttps://github.com/Dragon-Scaling/Recommendations_Service
typo "hhttps://github.com/Dragon-Scaling/Recommendations_Service"

2019-09-14 17:21 UTC, rfagg805 commented on README.md
> + - get('api/property/:propertyId/photos')
How about getting single Photo

2019-09-14 17:24 UTC, inyhsu requested changes
There is a typo in ReadMe.md

2019-09-14 18:59 UTC, justindchan commented
@rfagg805 correcting typos and adding api route for single photo. also refactoring schema and seed to use just one table now.

2019-09-16 18:15 UTC, justindchan commented on README.md
> + - get('api/property/:propertyId/photos')
fixed typos

2019-09-16 18:15 UTC, closed without merging